from django.db.models.aggregates import Count
from django.urls import path

from .views import *

urlpatterns = [
    path('account/', AccountView.as_view()),
    path('account/<uuid:pk>/', AccountView.as_view()),
    path('availability/', AvailabilityView.as_view()),
    path('availability/<uuid:pk>/', AvailabilityView.as_view()),
    path('bookmark/', BookmarkView.as_view()),
    path('bookmark/<uuid:pk>/', BookmarkView.as_view()),
    path('city/', CityView.as_view()),
    path('city/<uuid:pk>/', CityView.as_view()),
    path('congestion_rating/', CongestionRatingView.as_view()),
    path('congestion_rating/<uuid:pk>/', CongestionRatingView.as_view()),
    path('country/', CountryView.as_view()),
    path('country/<uuid:pk>/', CountryView.as_view()),
    path('currency/', CurrencyView.as_view()),
    path('currency/<uuid:pk>/', CurrencyView.as_view()),
    path('gym/', GymView.as_view()),
    path('gym/<uuid:pk>/', GymView.as_view()),
    path('gym_working_hours/', GymWorkingHoursView.as_view()),
    path('gym_working_hours/<uuid:pk>/', GymWorkingHoursView.as_view()),
    path('notification/', NotificationView.as_view()),
    path('notification/<uuid:pk>/', NotificationView.as_view()),
    path('ownership/', OwnershipView.as_view()),
    path('ownership/<uuid:pk>/', OwnershipView.as_view()),
    path('rating/', RatingView.as_view()),
    path('rating/<uuid:pk>/', RatingView.as_view()),
    path('recommendation/', RecommendationView.as_view()),
    path('recommendation/<uuid:pk>/', RecommendationView.as_view()),
    path('request_pause/', RequestPauseView.as_view()),
    path('request_pause/<uuid:pk>/', RequestPauseView.as_view()),
    path('request_period/', RequestPeriodView.as_view()),
    path('request_period/<uuid:pk>/', RequestPeriodView.as_view()),
    path('request/', RequestView.as_view()),
    path('request/<uuid:pk>/', RequestView.as_view()),
    path('user_token/', UserTokenView.as_view()),
    path('user_token/<uuid:pk>/', UserTokenView.as_view()),
    path('working_hours/', WorkingHoursView.as_view()),
    path('working_hours/<uuid:pk>/', WorkingHoursView.as_view()),
]
